config/routes.rb
Rails.application.routes.draw do

  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'

  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create, :destroy]
  resources :orders, only: [:new, :create, :show]

  devise_for :users
  namespace :admin do
    resources :products
    resources :products
    resources :brands
    resources :categories

  end

  root 'storefront#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
 # every brand has to have name and uniqueness 
  validates :name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  # line items depends on carts being there if not there destroy items
def subtotal
  #SQL version of summing which is much faster than Ruby
  line_items.select("SUM(quantity * price) AS sum")[0].sum
  # Ruby version of sum
  # line_items.to_a.sum {|item| item.total}
end

def add_product(product_id)
  product = Product.find(product_id)
  current_item = line_items.find_by(product_id: product_id)
  if current_item 
    current_item.quantity += 1
  else
    current_item = line_items.build(product: product, price: product.price)
  end
  current_item
end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true, uniqueness: true

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    price * quantity
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy

  validates :name, :address, :pay_type, :user_id, presence: true
  
  PAYMENT_TYPES = ["Check", "Credit Card", "COD", "Cash", "Bitcoin", "Paypal"]
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :brand
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  has_attached_file :avatar, 
  styles:{ medium: "300x300#", thumb: "100x100#"},
  default_url: "missing_:style.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_size :avatar, less_than: 3.megabytes, unless: Proc.new{
    |m| m[:avatar_file_name].blank?}

  validates_presence_of :name, :price, :quantity, :description, :brand, :category
  validates_numericality_of :price, greater_than_or_equal_to: 0.01
  validates_numericality_of :quantity, greater_than_or_equal_to: 0

  # validates :name, presence: true 
  # validates :price, presence: true 
  # validates :quantity, presence: true
  # validates :description, presence: true
  # validates :category_id, presence: true 
  # validates :brand_id, presence: true 
 
 def self.search_by_name_or_description(string)
  where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%")
    
  end 
# makes sure there are no line items referencing this product
  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items Present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  def edit
  end

  def destroy
    if @cart.destroy
      session[:cart_id] = nil
      flash[:notice] = "Cart successfully deleted"
      redirect_to shop_path
    else
      flash[:alert] = "Couldn't delete your cart."
      redirect_to edit_cart_path
    end
  end

end

# normally we would have   @cart = Cart.find()

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id) 

    if @line_item.save
      flash[:notice] = "#{product.name} was successfully added to your cart!"
      redirect_to shop_path
    else
      flash.now[:alert] = "Could not add #{product.name} to your cart."
      redirect_to :back
    end
  end
  def destroy
    @line_item = LineItem.find(params[:id])

    if @line_item.present?
      @line_item.destroy
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :authenticate_user!
  before_action :set_cart

  def new
    if @cart.line_items.empty?
      redirect_to shop_url, notice: "Your cart is empty."
      return
    end

    @order = Order.new
    @order.user_id = current_user.id
  end

  def show
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.add_line_items_from_cart(@cart)
    
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id]= nil
      redirect_to shop_url, notice: "Thanks for ordering from Store Tastic!"
    else
      render :new
    end


  end

private 

def order_params
  params.require(:order).permit(:name, :address, :pay_type, :user_id)
end


end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def index
    if params[:search]
      @products = Product.search_by_name_or_description(params[:search])
      if @products.empty?
        flash.now[:notice]= "Sorry, we're out of \"#{params[:search]}\", product for now"
        @products = Product.paginate(:page => params[:page], per_page: 10)
      end
    elsif params[:cat_id]
      @category=Category.find(params[:cat_id])
      @products = Product.where(category_id: params[:cat_id]).paginate(:page => params[:page], per_page: 10)
    else
      @products = Product.paginate(:page => params[:page], per_page: 10)
    end
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Store Tastic!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render '/layouts/navbar_links'  %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
      <ul class="nav navbar-nav">
        <!-- ************************ -->
        <!-- *Back Room Dropdown* -->
        <!-- ************************ -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Back Room <span class="caret"></span></a>
 
          <ul class="dropdown-menu">

            <li><%= link_to "Brands", admin_brands_path %></li>
            <li><%= link_to "Categories", admin_categories_path %></li>
            <li><%= link_to "Products", admin_products_path %></li>

          </ul>
            

      <!-- *********************** -->
      <!-- Shopping Dropdown -->
      <!-- *********************** -->
      <li class = "dropdonw">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"  aria-expanded="false"> Shop <span class="caret"></span></a>
        <ul class = "dropdown-menu" role="menu">
          <li><%= link_to "All Products", shop_path %></li>
          <!-- Loops through all the categories
           -->
          <% Category.all.each do |cat| %>
            <li> <%= link_to cat.name.capitalize, shop_path(cat_id: cat.id) %> </li>
            <% end %>
          
        </ul>

      </li>

          <li><%= link_to 'About', about_path %></li>




        </li>
      </ul>


      <!-- *********************** -->
      <!-- Right Navbar -->
      <!-- *********************** -->
      <ul class="nav navbar-nav navbar-right">
      <!-- *********************** -->
      <!-- Login and Out links -->
      <!-- *********************** -->
       <li><%= link_to fa_icon("shopping-cart", text:'Cart'), edit_cart_path %></li>
        <% if user_signed_in? %>
        <!-- ********************* -->
        <!-- Edit Cart             -->
        <!-- ********************* -->
         
          <li><%= link_to('Edit Account', edit_user_registration_path ) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Sign Up', new_user_registration_path ) %></li>

        <% end %>

      </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merchant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<p id="notice" class="alert-success"><%= notice %></p>

<%= yield %>

</body>
</html>